{% set name = "python-ldap" %}
{% set version = "3.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b2f6ef1c37fe2c6a5a85212efe71311ee21847766a7d45fcb711f3b270a5f79a

build:
  number: 0
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - wheel
    - pyasn1 >=0.3.7
    - pyasn1-modules >=0.1.5
    - openldap {{ openldap }}
  run:
    - python
    - pyasn1 >=0.3.7
    - pyasn1-modules >=0.1.5
    - openldap {{ openldap }}

test:
  requires:
    - pip
  imports:
    - ldap
    - ldap.controls
    - ldap.extop
    - ldap.schema
  commands:
    - pip check

about:
  home: https://www.python-ldap.org/
  license: PSF-2.0 and MIT
  license_family: Other
  license_file:
    - LICENCE
    - LICENCE.MIT
  summary: Python modules for implementing LDAP clients
  description: |
    python-ldap provides an object-oriented API to access LDAP directory servers
    from Python programs. Mainly it wraps the OpenLDAP client libs for that purpose.
  doc_url: https://www.python-ldap.org
  dev_url: https://github.com/python-ldap/python-ldap

extra:
  recipe-maintainers:
    - mariusvniekerk
